TrajectoryPlannerROS:
  max_vel_x: 0.15
  min_vel_x: 0.05

#  max_vel_theta: 1.0
  min_in_place_vel_theta: 0.4

  acc_lim_theta: 1.0
  acc_lim_x: 0.5
  acc_lim_y: 0.5

  yaw_goal_tolerance: 0.1
  xy_goal_tolerance: 0.15

  holonomic_robot: false
  meter_scoring: true
