obstacle_range: 4.0
raytrace_range: 3.0

#The footprint of the robot and associated padding
#footprint: [[x0, y0], [x1, y1], [xn, yn], [xn, yn]]
robot_radius: 0.15

#Cost function parameters
inflation_radius: 0.20

#Configuration for the sensors that the costmap will use to update a map
observation_sources: laser_scan_sensor

laser_scan_sensor: {sensor_frame: laser_frame, data_type: LaserScan, topic: scan, marking: true, clearing: true}

##Comment below are copy form "navigation_tutorials/navigation_stage/move_base_config/costmap_common_params.yaml"
##For this example we'll configure the costmap in voxel-grid mode
#map_type: voxel
#
##Voxel grid specific parameters
#origin_z: 0.0
#z_resolution: 0.2
#z_voxels: 10
#unknown_threshold: 9
#mark_threshold: 0
#
##Set the tolerance we're willing to have for tf transforms
#transform_tolerance: 0.3
#
##Obstacle marking parameters
#obstacle_range: 2.5
#max_obstacle_height: 2.0
#raytrace_range: 3.0
#
##The footprint of the robot and associated padding
#footprint: [[-0.325, -0.325], [-0.325, 0.325], [0.325, 0.325], [0.46, 0.0], [0.325, -0.325]]
#footprint_padding: 0.01
#
##Cost function parameters
#inflation_radius: 0.55
#cost_scaling_factor: 10.0
#
##The cost at which a cell is considered an obstacle when a map is read from the map_server
#lethal_cost_threshold: 100
#
##Configuration for the sensors that the costmap will use to update a map
#observation_sources: base_scan
#base_scan: {data_type: LaserScan, expected_update_rate: 0.4,
#  observation_persistence: 0.0, marking: true, clearing: true, max_obstacle_height: 0.4, min_obstacle_height: 0.08}