global_costmap:
  global_frame: map
  robot_base_frame: base_link
  update_frequency: 2
#Set static map to "false" if no existing map nor map server is used.
  static_map: true
  transform_tolerance : 4.0